FROM --platform=linux/amd64 golang:1.23.4-alpine

RUN apk add --no-cache bash curl git jq yq

# Copy over the configs
WORKDIR /configs
COPY ./configs/mainnet.config.yaml /configs/config.yaml

# Copy over the app
WORKDIR /app
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY ./ .

# Build the app & run it
RUN go build -o indexer ./cmd/indexer/main.go

EXPOSE 8085

CMD ["./indexer"]
