apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.labels.standaloneIndexer.name }}-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /indexer/status
    port: {{ .Values.ports.standaloneIndexer }}