Rpc:
  Host: localhost:5050
Api:
  Host: localhost
  Port: 8080
  AllowOrigins:
    - '*'
  AllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  AllowHeaders:
    - Content-Type
  Production: false
  Admin: true
Indexer:
  Host: localhost
  Port: 8085
Paymaster:
  Network: sepolia
  ApiUrl: "https://sepolia.paymaster.avnu.fi"
Modules:
  - AVNU_PAYMASTER
